// <auto-generated />
using PruebaNet8_BlazorServer_AndresCueva.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace PruebaNet8_BlazorServer_AndresCueva.Migrations
{
    [DbContext(typeof(ApplicationDbContextModelSnapshot))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PruebaNet8_BlazorServer_AndresCueva.Models.EmpleadosDTO", b =>
                {
                    b.Property<string>("nDimemp")
                        .HasColumnType("varchar(12)");
                
                    b.Property<string>("nomEmp")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("sexEmp")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<DateTime>("FecNac")
                        .IsRequired()
                        .HasColumnType("DateTime");

                    b.Property<float>("salEmp")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<float>("comisionE")
                       .IsRequired()
                       .HasColumnType("comisionE");

                    b.Property<string>("cargoE")
                      .IsRequired()
                      .HasColumnType("varchar(15)");

                    b.Property<string>("jefeID")
                      .IsRequired()
                      .HasColumnType("varchar(12)");

                    b.Property<string>("codDepto")
                   .IsRequired()
                   .HasColumnType("varchar(4)");

                    b.HasKey("nDimemp");

                    b.ToTable("Empleado");
                });
            #region"Departamentos models"
            modelBuilder.Entity("PruebaNet8_BlazorServer_AndresCueva.Models.DepartamentosDTO", b =>
            {
                b.Property<string>("codDepto")
                    .HasColumnType("varchar(4)");

                b.Property<string>("nombreDpto")
                    .IsRequired()
                    .HasColumnType("Varchar(20)");

                b.Property<string>("ciudad")
                    .IsRequired()
                    .HasColumnType("Varchar(15)");

                b.Property<int>("codDirector")
                    .IsRequired()
                    .HasColumnType("Varchar(12)");
            });
            #endregion
            #region"Mas models"
           
            #endregion
#pragma warning restore 612, 618
        }
    }
}
